### ISSUE TITLE
有可能的话，希望做一个Macos的版本。

### ISSUE THREAD

**Issue by unicorn1009** [imlinhanchao/KeyGenius#1]
昨天晚上写了一晚上文档，最后关闭的时候手残点到了取消保存，真的整个人都崩了

**Comment by imlinhanchao** [comment]
深表同情，我研究一下。😂

**Comment by imlinhanchao** [comment]
现学现卖，可能有些 Bug🤔，有问题再提 Issue。在 [Release](../releases/tag/1.0.5) 下载。注意需加入 Mac 的隐私列表，因为需要模拟发送键盘消息。
