### ISSUE TITLE
windows 10 下使用提示缺少组件

### ISSUE THREAD

**Issue by pointedhat32167** [imlinhanchao/KeyGenius#2]
libgcc_s_dw2-1.dll
libstdc++-6.dll

由于找不到 libgcc_s_dw2-1.dll，无法继续执行代码。重新安装程序可能会解决此问题。 
由于找不到 libstdc++-6.dll，无法继续执行代码。重新安装程序可能会解决此问题。

**Comment by imlinhanchao** [comment]
Windows可以下载 1.0.3 版本，1.0.4 开始为了做 Mac 版本更换为 Qt 架构，我再看看是怎么回事儿。

**Comment by imlinhanchao** [comment]
已修正，可到此[下载](../releases/tag/1.0.6.win)

**Comment by LZH200** [comment]
由于找不到 libgcc_s_dw2-1.dll，无法继续执行代码。重新安装程序可能会解决此问题
windows7
